name: Publish Docker Images
on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          include:
            - dockerfile: ./toolchain-base/Dockerfile
              image: ghcr.io/xpl0itu/toolchain-base
            - dockerfile: ./devkita64/Dockerfile
              image: ghcr.io/xpl0itu/devkita64
            - dockerfile: ./devkitarm/Dockerfile
              image: ghcr.io/xpl0itu/devkitarm
            - dockerfile: ./devkitppc/Dockerfile
              image: ghcr.io/xpl0itu/devkitppc
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,value=latest

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Get date for tag
        run: echo "DATE_TAG=$(date +"%Y%m%d")" >> $GITHUB_ENV

      - name: Build and push ${{ matrix.image }} Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          tags: |
            "${{ matrix.image }}:${{ env.DATE_TAG }}"
            "${{ matrix.image }}:latest"
          labels: ${{ steps.meta.outputs.labels }}
          push: true
